FROM ubuntu:14.04
MAINTAINER Thierry Neel <Thierry.Neel@verifone.com>
RUN apt-get update
# Node + npm + git
RUN apt-get -y install nodejs
RUN apt-get -y install npm
RUN sudo ln -s /usr/bin/nodejs /usr/bin/node
#curl
RUN apt-get -y install curl
# Hapi
RUN npm install hapi

RUN npm install filterService
# Expose ports.
# - 80: HTTP
EXPOSE 80
# Start
RUN cd node_modules
#RUN node filterService/startServer.js